target_db: td_test

job_priority: -1

topk_predict: 5

past_ndays: 60
num_features: 30

train_rate: 0.7

# language of documents
# if english => english: true, japanese: false
# if japanese => english: false, japanese: true
english: false
japanese: true

# valid age range
min_age: 15
max_age: 95

# RandomForest
rf_seed: 71
rf_trees: 15
rf_num_train_parallel: 4
rf_max_depth: 30
min_split: 3
min_samples_leaf: 1

# over/down sampling
min_class_weight: 0.8
max_class_weight: 4.0

# heuristic calibration
f15_factor: 1.0
f20_factor: 1.0
f25_factor: 1.0
f35_factor: 1.0
f50_factor: 1.0
m15_factor: 1.0
m20_factor: 1.0
m25_factor: 1.0
m35_factor: 1.0
m50_factor: 1.0

#f15_factor: 1.1
#f20_factor: 1.4
#f25_factor: 0.75
#f35_factor: 0.6
#f50_factor: 0.7
#m15_factor: 1.1
#m20_factor: 1.4
#m25_factor: 1.2
#m35_factor: 0.75
#m50_factor: 0.35
