# For advanced config options, please check these URLs.
# @see https://docs.treasuredata.com/articles/data-connector-postgresql
# @see https://github.com/embulk/embulk-input-jdbc/tree/master/embulk-input-postgresql
---
in:
  type: postgresql
  host: ${secret:postgresql.host}
  port: ${secret:postgresql.port}
  user: ${secret:postgresql.user}
  password: ${secret:postgresql.password}
  schema: public
  database: source_db
  query: "select * from `source_table` limit 10"
out: {}
exec: {}
filters: []
